update to circleci/node:13-browsers
Following error is reproducing during yarn build with yarn v1.15.2. Local yarn v1.21.1 is used without any problem, so we update docker container to 13-browsers which uses yarn v.1.22.4.

Error: [BABEL] /home/circleci/project/src/index.js: Cannot find module 'gensync' (While processing: "/home/circleci/project/node_modules/babel-preset-react-app/index.js")